// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqprlhzyyfvjmzetcyrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcHJsaHp5eWZ2am16ZXRjeXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMjQ1OTksImV4cCI6MjA3NDgwMDU5OX0.sRgOmDSlukiMdrb0jhd1cwYz86-hzjWnH-Ef547uBGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});